"""Recruiting Agency OS — Part 4: Bonuses (365 CSV + 3 DOCX) + PDFs + PPTX Canva templates"""
import os, csv, random
from docx import Document
from docx.shared import Pt, RGBColor, Inches
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import cm
from pptx import Presentation
from pptx.util import Inches as PInches, Pt as PPt, Emu
from pptx.dml.color import RGBColor as PRGB
from pptx.enum.text import PP_ALIGN
from pptx.util import Inches

BASE = "/home/user/oqul-phase55-production/recruiting-agency-os/Ultimate_Recruiting_Agency_Operating_System/"

def doc(filename, title, subtitle, sections):
    d = Document()
    t = d.add_paragraph(title); t.style = d.styles['Normal']
    t.runs[0].bold = True; t.runs[0].font.size = Pt(14)
    t.runs[0].font.color.rgb = RGBColor(0x0F,0x34,0x60)
    if subtitle:
        s = d.add_paragraph(subtitle); s.style = d.styles['Normal']
        s.runs[0].font.size = Pt(10)
        s.runs[0].font.color.rgb = RGBColor(0x7F,0x8C,0x8D)
    for section in sections:
        if isinstance(section, str):
            d.add_paragraph(section); continue
        heading, items = section
        h = d.add_heading(heading, level=1)
        h.runs[0].font.color.rgb = RGBColor(0x0F,0x34,0x60)
        for item in items:
            if isinstance(item, tuple) and item[0] == '•':
                d.add_paragraph(item[1], style='List Bullet')
            else:
                d.add_paragraph(str(item))
    d.save(BASE + filename)
    print(f"  ✓ {filename}")

# ── 11_BONUSES ────────────────────────────────────────────────────────────────

# 365 Captions CSV
categories = {
    "Hiring Tips": [
        "The best candidates are rarely actively looking. Build your passive pipeline now.",
        "A slow hiring process is the #1 reason top candidates drop out. Move fast.",
        "Your job description is your first interview. Make it compelling.",
        "Salary transparency increases qualified applicant rates by 30–40%. Show the range.",
        "The most important interview question: Would you rehire this person?",
        "Structured interviews (same questions, all candidates) reduce bias and improve hire quality.",
        "Culture fit is real — but don't let it become a code word for homogeneity.",
        "Reference checks are underused. Call the references; don't just email them.",
        "The first 90 days predict long-term success more than any interview performance.",
        "Counter-offers: 80% of candidates who accept one are gone within 12 months.",
        "A one-week delay in scheduling costs you the candidate 40% of the time.",
        "Top performers want to work with other top performers. Sell the team, not just the role.",
        "Remote work policies matter more than office perks for most candidates in 2025.",
        "Always tell rejected candidates. Every rejected candidate is a future applicant or referral.",
        "Your Glassdoor score affects your ability to attract talent. Monitor and respond.",
        "Onboarding doesn't end after day one. 30/60/90-day check-ins prevent early exits.",
        "Hiring bias often hides in 'culture fit' language. Define culture with behaviors, not vibes.",
        "Panel interviews reduce bias. Diverse panels attract diverse talent.",
        "Ask for candidate feedback after every interview process. Learn from both wins and losses.",
        "The cost of a bad hire is estimated at 30–150% of annual salary. Invest in screening.",
        "Internal referrals have higher retention rates than any other source.",
        "Pay attention to candidates' questions — they reveal their priorities.",
        "Speed of response signals how much you value people.",
        "An offer is not a close. Manage counter-offer risk proactively.",
        "The best hiring managers sell the opportunity as hard as candidates sell themselves.",
        "Video interviews have 40% higher no-show rates than phone screens. Confirm twice.",
        "Always ask for a 1–10 interest score after each interview stage.",
        "Hiring for potential over experience produces your most loyal employees.",
        "Your recruiter is an extension of your brand. Brief them on culture.",
        "Candidate experience = employer brand. Treat every applicant like a future customer.",
    ],
    "Career Advice": [
        "Your resume gets 6 seconds. Make the first 3 lines impossible to skip.",
        "Quantify everything: 'Managed a team' vs 'Led a team of 8 that grew revenue by 40%'.",
        "LinkedIn is your digital first impression. Update it before you need it.",
        "Negotiate every offer. Most companies expect it and build room into the offer.",
        "The best career advice: build skills that compound. Communication never goes out of style.",
        "Leaving for a 15% raise is usually not worth it. Leaving for growth always is.",
        "Counter-offers feel flattering. They're usually a short-term fix. Know your worth.",
        "A strong network will open more doors than a perfect resume.",
        "Ask for feedback after every rejection. Most people are too shy to ask.",
        "Your personal brand is what people say about you when you're not in the room.",
        "Career pivots are easier in your 20s and 30s. Don't wait for perfect readiness.",
        "The best interviews feel like great conversations. Prepare to have one.",
        "Salary research is not optional. Know your market before the offer call.",
        "Take the call from the recruiter. You don't have to take the job.",
        "Visible work beats invisible work. Share what you're building.",
        "Ask your references if they'd give a strong recommendation before you list them.",
        "The STAR method works. Practice your stories until they're reflexive.",
        "First job is about learning, not salary. Second job is where comp starts to matter.",
        "Thank-you emails after interviews: 70% of candidates skip them. Be in the 30%.",
        "Job hopping is less stigmatized than ever — but have a clear narrative.",
        "Your skills section on LinkedIn is indexed for recruiter searches. Optimize it.",
        "Request a meeting summary after every interview so expectations are clear.",
        "Don't apply to 200 jobs. Apply to 20 very well.",
        "Culture beats salary until the bills pile up. Know which season you're in.",
        "Ask about the path from this role — not just what the role is.",
        "The gap on your resume is not as scary to employers as you think. Own it.",
        "Your work speaks; your title whispers. Do the work first.",
        "Mentors open doors. Sponsors walk through them with you. Find both.",
        "A bad job is still worth 2 years if it teaches you what you don't want.",
        "Negotiating doesn't cost you the offer. Staying silent does cost you money.",
    ],
    "Industry Insights": [
        "The talent market in [niche] is shifting. Passive candidates now outnumber active 4:1.",
        "AI is changing recruiting. The recruiters who adapt will thrive. The others won't.",
        "Remote-first companies have access to a global talent pool. That's your competition.",
        "Skills-based hiring is replacing degree requirements in many industries.",
        "The average time-to-fill is 44 days. The best recruiters average under 18.",
        "Ghosting goes both ways. Candidates ghost employers just as often as employers ghost candidates.",
        "Employer brand now rivals salary as a top candidate decision factor.",
        "Gen Z prioritizes values alignment, flexibility, and purpose. Adjust your pitch.",
        "The gig economy has normalized portfolio careers. Expect non-linear resumes.",
        "Pay transparency laws are expanding. Proactively disclosing ranges is a competitive advantage.",
        "AI-generated resumes are common. Human screening judgment matters more than ever.",
        "Workforce planning is the new recruiting. Hire ahead of the need, not after.",
        "LinkedIn has 900M+ members. Most of them are reachable with the right message.",
        "Recruiting agencies that specialize outperform generalists by 30% on time-to-fill.",
        "The best candidates have 3–4 conversations happening simultaneously. Speed wins.",
        "Diversity hiring isn't just ethical — companies with diverse teams outperform peers by 35%.",
        "Automation handles sourcing. Human judgment handles selection. Know the difference.",
        "Soft skills (communication, adaptability) predict long-term success more than hard skills.",
        "The hidden job market (roles never posted) accounts for 70% of hires.",
        "Employee referral programs have the highest ROI of any sourcing channel.",
        "Data-driven recruiting is replacing gut instinct. Track your metrics religiously.",
        "Onboarding quality predicts 90-day retention. Invest here as much as in hiring.",
        "The war for talent isn't over. It's just moved to niche and specialized roles.",
        "Work-life balance is now table stakes. Benefits and culture are the differentiators.",
        "Burnout is the #1 reason senior professionals leave roles. Address it in your employer brand.",
        "Boomerang employees (those who return) perform better and onboard 50% faster.",
        "Video job descriptions get 4x more engagement than text-only postings.",
        "The recruiter who builds genuine relationships will always win over the algorithm.",
        "Candidate experience directly correlates with revenue — unhappy candidates share their experience.",
        "Internship programs are your best pipeline for junior talent. Invest early.",
    ],
    "Engagement": [
        "What's the biggest hiring mistake you've made — and what did you learn from it?",
        "Hot take: A great candidate beats a perfect resume. Agree or disagree?",
        "What's the one interview question that tells you the most? Drop it below.",
        "If you could change ONE thing about the hiring process, what would it be?",
        "Should companies always disclose salary ranges? Yes or no?",
        "What's the best career advice you ever received? Share below.",
        "Remote, hybrid, or in-office? What's your preference in 2025 and why?",
        "What's the one skill you wish you had learned earlier in your career?",
        "Tell me: what made you say yes to your current role?",
        "What's the most overrated interview question? And what would replace it?",
        "What's the first thing you check when evaluating a new job opportunity?",
        "Best professional decision you've made in the last 5 years?",
        "What does your ideal recruiter relationship look like?",
        "If you could tell hiring managers one thing, what would it be?",
        "What's the most memorable thing a recruiter has done for you?",
        "What's your biggest fear about changing jobs?",
        "What's the first red flag you notice in a job description?",
        "If salary wasn't a factor, what would you do professionally?",
        "How do you know a company has a great culture before you join?",
        "What's a skill that's undervalued in most workplaces?",
        "Has a counter-offer ever worked out for you? What happened?",
        "What's your biggest time-waster in the interview process?",
        "What's the worst piece of career advice you've ever received?",
        "What's the one thing your employer does that keeps you from leaving?",
        "How do you decide between two job offers that are similar in comp?",
        "What career path did you NOT take — and do you ever wonder 'what if'?",
        "What's the most underrated trait in a great manager?",
        "What question do you wish more interviewers asked?",
        "What's the fastest you've ever made a hiring decision? Was it the right call?",
        "What does work-life balance actually mean to you?",
    ],
    "Social Proof": [
        "We helped a fintech startup fill a VP Engineering role in 9 days. The candidate had 5 competing offers.",
        "A client came to us after 4 months of internal searching. We placed their Head of Sales in 12 days.",
        "One of our placed candidates just got promoted. That's a win we get to celebrate too.",
        "We've placed 50+ professionals in [niche] roles this year. Not one placement under 85% satisfaction.",
        "A recent client told us: 'This was the easiest hiring process we've ever had.' That's the goal.",
        "When candidates say they were treated with respect throughout, that's what we build for.",
        "Guarantee period ends: client says the hire was the best decision they made all year. This is why we do it.",
        "Candidate relocated across the country for this role. 6 months in — loving every day.",
        "A client who placed 1 person with us 3 years ago. Now we've placed 14 across their team.",
        "We placed a candidate who had been looking for 6 months on their own. We found their role in 3 weeks.",
        "When a client calls to say 'your candidate just got their first promotion,' everything clicks.",
        "Our average placement is still employed and thriving at the 12-month mark. Track records matter.",
        "A candidate who feared their career was 'too niche' — placed in their dream role in 3 weeks.",
        "A startup that couldn't afford top talent found a way through creative comp structure. We helped build it.",
        "A mid-career professional changed industries. We helped them reframe their story. They got the offer.",
        "90 days after placement: client says 'how soon can you find us another one?' Best metric we have.",
        "We worked with a candidate for 18 months before the right role appeared. Patience wins.",
        "Three of our placed candidates became managers within 18 months. We hire ahead of the curve.",
        "Client feedback: 'The profiles you sent were better than what we got from 3 other agencies combined.'",
        "A 2-week search for a notoriously hard-to-fill compliance role. Right candidate, right time.",
        "The candidate turned down a higher offer to take the one we found. Culture over comp.",
        "Six months post-placement, our candidates average 94% satisfaction with the role. We ask.",
        "We've partnered with this client for 4 years and 22 placements. That's trust.",
        "A recruiter who follows through on every commitment. That's how you get repeat business.",
        "We didn't fill the role the first time. We told the client why and fixed it. They came back.",
        "An executive who said 'I wasn't looking.' Four conversations later, career-defining move made.",
        "Speed matters: offer accepted before the candidate had time to reconsider other options.",
        "Client called us first after a surprise vacancy. We had a shortlist in 4 days.",
        "Every placement starts with genuinely listening to what the client and candidate actually need.",
        "The best recruiting isn't transactional. It's relational. We're playing a long game.",
    ],
    "Myth Busting": [
        "Myth: 'We can find our own candidates on LinkedIn.' Truth: The top 20% aren't browsing. They need to be found.",
        "Myth: 'Agency fees are too expensive.' Truth: An unfilled role costs 2–3x the monthly salary per month.",
        "Myth: 'We'll just post on Indeed.' Truth: 70% of top hires never see your job posting.",
        "Myth: 'Recruiting is just sending resumes.' Truth: Screening, assessment, and management take 40+ hours per role.",
        "Myth: 'We can't afford a recruiter right now.' Truth: You can't afford a 90-day vacancy.",
        "Myth: 'The best candidates are always looking.' Truth: The best candidates rarely are.",
        "Myth: 'We need 10 interviews to be sure.' Truth: More interviews = more drop-off, not better decisions.",
        "Myth: 'A great resume means a great employee.' Truth: The best performers often have atypical resumes.",
        "Myth: 'We just need to post higher salary.' Truth: Candidates want growth and culture, not just comp.",
        "Myth: 'A recruiter is a middleman.' Truth: A recruiter is a market intelligence partner.",
        "Myth: 'Counter-offers solve retention.' Truth: 80% of counter-offer acceptances leave within 12 months.",
        "Myth: 'Hiring is just HR's job.' Truth: The best hiring managers own the process end-to-end.",
        "Myth: 'AI will replace recruiters.' Truth: AI handles search. Humans handle judgment.",
        "Myth: 'We know what we need.' Truth: The intake process almost always reveals something new.",
        "Myth: 'Candidates will wait.' Truth: Great candidates rarely will.",
        "Myth: 'Anyone can recruit.' Truth: Great recruiting is a learnable skill. Most people skip the learning.",
        "Myth: 'We've always done it this way.' Truth: The hiring market has changed more in 5 years than the prior 20.",
        "Myth: 'We don't need a specialist recruiter.' Truth: Generalists miss niche talent. Specialists find it.",
        "Myth: 'The perfect candidate exists.' Truth: The right candidate and the perfect candidate are different people.",
        "Myth: 'References don't matter.' Truth: One reference call can save you from a 6-figure mistake.",
        "Myth: 'Video interviews are just as good as in-person.' Truth: For assessment of some traits, yes. Not all.",
        "Myth: 'Candidates don't care about our brand.' Truth: Glassdoor reviews affect offer acceptance rates directly.",
        "Myth: 'Skills tests tell us everything.' Truth: Skills tests reveal competency, not character.",
        "Myth: 'Remote workers are less productive.' Truth: Managed well, they're 13% more productive on average.",
        "Myth: 'The candidate who asks for more is greedy.' Truth: The candidate who negotiates is the one who knows their worth.",
        "Myth: 'Speed hiring leads to bad hires.' Truth: Indecision leads to bad hires. Speed with process leads to great ones.",
        "Myth: 'Cover letters don't matter.' Truth: A great one still gets noticed. A bad one still screens people out.",
        "Myth: 'We can onboard people quickly.' Truth: Effective onboarding takes 3–6 months. Plan accordingly.",
        "Myth: 'Diversity hiring lowers the bar.' Truth: Diverse hiring widens the pool. That raises the bar.",
        "Myth: 'Culture fit means similar to us.' Truth: Culture fit means someone who thrives in how you work.",
    ],
    "Authority": [
        "After [X] years in recruiting, here's what actually predicts long-term placement success.",
        "I've reviewed 500+ resumes this year. Here's what makes a great one.",
        "The one question I ask in every client kickoff that changes the entire search.",
        "Why I stopped doing retained searches for certain role types — and what I do instead.",
        "The sourcing method that consistently finds candidates other recruiters miss.",
        "How I evaluate a candidate in the first 3 minutes of a phone screen.",
        "The fee structure I recommend to clients and why (it's not always contingency).",
        "Why I turned down a search last month — and why that matters.",
        "The single best investment I've made in my recruiting career.",
        "What 10 years of recruiting taught me about human behavior in career transitions.",
        "The non-obvious reason most searches fail (it's rarely the candidate market).",
        "How I handle counter-offers so my candidates don't disappear at the finish line.",
        "The boolean search string I use for [role] that no one else is using.",
        "Why I always present candidates in batches of 3, not one at a time.",
        "The intake question that saves me 3 weeks of misaligned searching.",
        "My take on AI-generated resumes and how I spot them in 30 seconds.",
        "The system I use to manage 12 active searches simultaneously without burning out.",
        "Why I always call references rather than emailing them.",
        "How I built my client base from 0 to [X] clients without cold calling (mostly).",
        "The market insight I share with every client before kicking off a search.",
        "What makes a 'good recruiter' vs. a 'great recruiter' — in my experience.",
        "The deal I almost lost — and what saved it at the last minute.",
        "Why I recommend salary ranges in job postings to every client.",
        "The offer management approach that's saved me from a dozen fall-throughs.",
        "What I've learned about passive candidate outreach after [X] years of testing.",
        "My honest review of the top ATS systems I've used.",
        "The follow-up system that's generated 40% of my new business in the last year.",
        "Why I never submit more than 5 candidates — even when clients want more.",
        "The question I ask to predict whether a candidate will actually accept the offer.",
        "How I think about building a niche — and why generalist recruiting is getting harder.",
    ],
    "Lead Generation": [
        "Are you struggling to fill a [role] position? Send me a DM — I have pre-vetted candidates ready.",
        "We have 3 [role] candidates available to interview this week. DM me for profiles.",
        "Is your [department] understaffed going into Q[X]? Let's talk about a proactive hiring plan.",
        "We specialize in [niche] roles. If you're hiring in this space, let's connect this week.",
        "New to working with a recruiting agency? I offer a complimentary 20-minute hiring strategy call.",
        "If you have an open [role] that's been hard to fill, DM me — I probably know someone.",
        "Hiring for a [role] role? I can have qualified profiles to you in 5 business days.",
        "Are you a [industry] company planning your Q[X] hiring? Let's build the plan now.",
        "We just placed a [role] for a [industry] client in 10 days. Want to know how? Let's connect.",
        "I have a [role] candidate with [X years] experience looking for their next move. Want a profile?",
        "Is your team short-staffed because of a recent departure? I can help you move fast.",
        "We offer a [90]-day guarantee on all placements. Zero-risk way to try working with us.",
        "I help [industry] companies fill [role] roles in under 3 weeks. Interested? Let's talk.",
        "If you've been burned by agencies before, I want to show you a better experience. DM me.",
        "What does a vacancy cost your business per month? I can help you close it faster.",
        "I'm currently working with candidates in [niche] who are ready to move. Is your team hiring?",
        "Thinking about hiring in [Year]? The best candidates are being recruited now. Get ahead of it.",
        "I have a [role] opening with a great client. Is your next role [location/remote]? Let's talk.",
        "My average time-to-fill is [X] days. What's yours? I can probably help cut it in half.",
        "If you're on the fence about using a recruiter, let's start with a no-commitment call.",
        "Hiring season is here. Are you prepared with a plan, or reacting to vacancies?",
        "We fill [niche] roles that most agencies can't. What's your hardest-to-fill position?",
        "I offer a [15]-minute hiring assessment call at no cost. Worth it to see if we can help?",
        "Your competitors are building their teams now. Are you?",
        "Send me your job description. I'll tell you honestly if I can help within 24 hours.",
        "Candidate shortages are real in [niche]. But they're not universal. I know where the talent is.",
        "What if filling your next role took 10 days instead of 60? Let's make that happen.",
        "A recruiter who specializes > a recruiter who does everything. That's how I operate.",
        "I'm accepting [X] new client searches this quarter. Is your role one of them?",
        "The best time to talk to a recruiter is before you're desperate. Let's connect now.",
    ],
    "Community": [
        "Shoutout to every hiring manager who gives candidates real, timely feedback. You're the rare ones.",
        "To the recruiters grinding through a tough market: the work you do matters.",
        "Happy to answer any recruiting or job search questions in the comments today. Ask me anything.",
        "If you're a [niche] professional open to opportunities — DM me. I have active searches right now.",
        "Tag a recruiter who changed your career trajectory. They deserve the recognition.",
        "Which city/market are the best [role] candidates coming from right now? Let's discuss.",
        "I'm sharing everything I know about hiring in [niche] this year. Follow along.",
        "For the job seekers in my network: your next role is out there. Keep going.",
        "A reminder that everyone in your network is two conversations away from an opportunity.",
        "Celebrating [placement anniversary] years of helping [niche] professionals find great roles.",
        "If you're a [role] professional who'd like to stay in my network for future opportunities — connect below.",
        "To every candidate who trusted us with their career search this year — thank you.",
        "Free resource: [brief insight on market]. Save this for your next job search.",
        "The best recruiters I know are also great connectors. Let's all be better connectors.",
        "What's your [niche] network missing? What connections would help most? Let's solve it together.",
        "A thank you to the clients who trust us with their most important hire of the year.",
        "Connecting [professionals] with [companies] is more than a job — it changes lives.",
        "Welcome to all my new followers. I share [content pillars] here. Glad you're here.",
        "If you know someone navigating a job search right now — share this with them. Small gestures matter.",
        "The recruiting community is stronger when we share what's working. Let's do more of that.",
    ],
    "Promotions": [
        "New service: [30]-minute complimentary hiring strategy session for growing companies. Book yours this week.",
        "We've expanded our [niche] practice. If you're hiring in [role type], we can help.",
        "Announcing: our new contract/interim recruiting service. Flexible, fast, no long-term commitment needed.",
        "If you've been thinking about working with us, now is a great time — our schedule has [X] openings.",
        "Introductory offer: First search at [X]% (reduced from [X]%) for new clients who sign this month.",
        "We just launched our [niche] salary guide for [Year]. DM 'salary' to get your free copy.",
        "New: our candidate referral program. Refer someone we place and earn [reward].",
        "Our Q[X] hiring seminar is filling up. [X] spots left — DM me to reserve yours.",
        "Partnering with [partner type] to provide [niche] companies with a full HR + recruiting service.",
        "Now accepting searches for [Year] Q1. Our calendar is filling up — reach out this week.",
    ],
}

rows = []
n = 1
all_cats = list(categories.keys())
while n <= 365:
    cat = all_cats[(n-1) % len(all_cats)]
    captions = categories[cat]
    caption = captions[(n-1) // len(all_cats) % len(captions)]
    rows.append([str(n), cat, caption, "#recruiting #hiring #recruitingagency #talentacquisition #careers"])
    n += 1

with open(BASE + "11_BONUSES/365_Recruiting_Content_Captions.csv", "w", newline="", encoding="utf-8-sig") as f:
    w = csv.writer(f)
    w.writerow(["Day","Category","Caption","Hashtags"])
    w.writerows(rows)
print("  ✓ 11_BONUSES/365_Recruiting_Content_Captions.csv")

doc("11_BONUSES/100_Recruiting_Content_Ideas.docx",
    "100 Recruiting Content Ideas",
    "Recruiting Agency Operating System | Bonuses",
    [
        ("HIRING TIPS (1–25)", [
            ("•", "The 3 questions every hiring manager should ask in a first interview"),
            ("•", "Why most job descriptions repel great candidates"),
            ("•", "How to evaluate candidates beyond their resume"),
            ("•", "The real cost of a vacant role (with numbers)"),
            ("•", "5 signs an interview is going well from a recruiter's perspective"),
            ("•", "What 'culture fit' should actually mean in your hiring process"),
            ("•", "How to move fast without rushing — the 48-hour rule"),
            ("•", "Why your best candidates are still employed — and how to reach them"),
            ("•", "The intake meeting question that changes every search"),
            ("•", "How long should your hiring process take? (And why shorter is usually better)"),
            ("•", "Reference checks: what to ask and what to listen for"),
            ("•", "The difference between a good hire and a great one"),
            ("•", "Salary benchmarking: how to set comp that actually attracts talent"),
            ("•", "How to write a job description that top candidates actually read"),
            ("•", "What candidates want that isn't salary"),
            ("•", "The one metric that predicts placement success more than anything else"),
            ("•", "How to handle competing offers without losing candidates"),
            ("•", "Why the 90-day mark is the most important checkpoint"),
            ("•", "The most common reason candidates decline offers"),
            ("•", "How to build a talent pipeline before you have an open role"),
            ("•", "What your Glassdoor score is actually telling you"),
            ("•", "Structured vs. unstructured interviews: the data"),
            ("•", "How to create an onboarding plan that retains new hires"),
            ("•", "The candidate red flags you might be ignoring"),
            ("•", "Why your hardest-to-fill role is probably misaligned, not unfillable"),
        ]),
        ("CAREER ADVICE (26–50)", [
            ("•", "How to negotiate your salary without losing the offer"),
            ("•", "The resume format that gets recruiter attention in 6 seconds"),
            ("•", "LinkedIn profile: the 5 sections that matter most"),
            ("•", "How to answer 'What's your salary expectation?' confidently"),
            ("•", "When to accept and when to walk away from a job offer"),
            ("•", "How to job search while employed — without getting caught"),
            ("•", "The thank-you email template that gets remembered"),
            ("•", "Why most people bomb the 'tell me about yourself' question"),
            ("•", "Career pivots: how to reframe your story for a new industry"),
            ("•", "How to build relationships with recruiters before you need them"),
            ("•", "The counter-offer decision framework"),
            ("•", "What to do in your first 30 days at a new job"),
            ("•", "How to ask for a raise — and get one"),
            ("•", "The STAR method: how to answer behavioral questions perfectly"),
            ("•", "What to do when you're rejected after a final-round interview"),
            ("•", "How to evaluate company culture before you accept the offer"),
            ("•", "The questions to ask at the end of every interview"),
            ("•", "How to deal with a long job search without losing confidence"),
            ("•", "Why you should always tell your recruiter your real salary expectations"),
            ("•", "Reference checklist: how to prepare your references"),
            ("•", "How to negotiate remote work flexibility in your offer"),
            ("•", "The one-page resume rule: when it applies and when it doesn't"),
            ("•", "Career growth vs. job title: which matters more?"),
            ("•", "How to job search with a gap in your resume"),
            ("•", "What top performers do differently in their first year"),
        ]),
        ("RECRUITING INDUSTRY (51–75)", [
            ("•", "How the recruiting market has changed in the last 3 years"),
            ("•", "Contingency vs. retained: which model is right for your search"),
            ("•", "The best tools for sourcing candidates in [Year]"),
            ("•", "How AI is changing the recruiting industry"),
            ("•", "Why specialized recruiters outperform generalists"),
            ("•", "The hidden job market: fact or fiction?"),
            ("•", "Recruiter KPIs that actually matter"),
            ("•", "How to evaluate a recruiting agency before you sign"),
            ("•", "The guarantee clause: what to look for"),
            ("•", "Why passive candidates are the most valuable part of the talent pool"),
            ("•", "The evolution of the candidate experience"),
            ("•", "How to build a referral network as a recruiter"),
            ("•", "The business case for diversity hiring (with data)"),
            ("•", "What employers get wrong about the job market"),
            ("•", "The future of recruiting: what survives automation"),
            ("•", "Compensation data sources every recruiter should know"),
            ("•", "Building a personal brand as a recruiter in 2025"),
            ("•", "The LinkedIn strategy that fills your pipeline with inbound leads"),
            ("•", "How top recruiting agencies handle offer fall-throughs"),
            ("•", "EEOC basics every recruiter needs to know"),
            ("•", "Retained search 101: what clients need to know"),
            ("•", "The metric that measures recruiting effectiveness better than time-to-fill"),
            ("•", "How to handle a client who keeps rejecting candidates"),
            ("•", "Why counter-offers are almost always a mistake (data-backed)"),
            ("•", "The skills that make a great recruiter in any market"),
        ]),
        ("ENGAGEMENT & STORYTELLING (76–100)", [
            ("•", "My biggest mistake as a recruiter and what it taught me"),
            ("•", "The placement that almost didn't happen — and how we saved it"),
            ("•", "What my first year in recruiting taught me about people"),
            ("•", "The candidate who turned down $30K more to take the right role"),
            ("•", "A day in the life: what recruiting actually looks like"),
            ("•", "The thank-you call that reminded me why I do this work"),
            ("•", "The hardest conversation I've had with a client — and how it ended"),
            ("•", "What changed when I started treating candidates like clients"),
            ("•", "The question I ask at the end of every search that makes clients come back"),
            ("•", "Why I almost quit recruiting — and what made me stay"),
            ("•", "The role I couldn't fill — and what I learned from it"),
            ("•", "My framework for staying productive when the market is slow"),
            ("•", "What the best hiring managers have in common"),
            ("•", "The placement that changed a candidate's life trajectory"),
            ("•", "Behind the scenes of a $40,000 retained search"),
            ("•", "What it takes to be a recruiter clients trust completely"),
            ("•", "The 3 calls that happen before every successful placement"),
            ("•", "What I've learned from 500+ candidate conversations"),
            ("•", "The follow-up message that saved a deal about to fall apart"),
            ("•", "Why relationships in this industry outlast any single placement"),
            ("•", "The moment I knew I had found the right candidate"),
            ("•", "What I wish clients knew before our first call"),
            ("•", "The resume that made me call immediately — here's what it had"),
            ("•", "What a slow month in recruiting teaches you about the business"),
            ("•", "The question a candidate asked that told me everything I needed to know"),
        ]),
    ])

doc("11_BONUSES/Recruiter_Success_Framework.docx",
    "Recruiter Success Framework",
    "Recruiting Agency Operating System | Bonuses",
    [
        ("THE 5 PILLARS OF RECRUITING EXCELLENCE", [
            "Mastering recruiting comes down to five interconnected pillars. Strong recruiters excel in all five; great recruiters optimize them continuously.",
        ]),
        ("PILLAR 1 — MARKET KNOWLEDGE", [
            ("•", "Know compensation benchmarks for every role you fill"),
            ("•", "Understand the talent supply/demand balance in your niche"),
            ("•", "Track hiring trends, layoffs, and expansion in your industry"),
            ("•", "Know who is hiring, who just funded, and who is contracting"),
        ]),
        ("PILLAR 2 — RELATIONSHIPS", [
            ("•", "Clients: Deep trust built through consistent delivery and honesty"),
            ("•", "Candidates: Respect built through communication and follow-through"),
            ("•", "Network: Referral partners, thought leaders, and community connections"),
            ("•", "Invest in relationships before you need them — consistently"),
        ]),
        ("PILLAR 3 — PROCESS", [
            ("•", "Consistent intake → sourcing → screening → submittal → close process"),
            ("•", "Every step documented and repeatable"),
            ("•", "Metrics tracked at each stage to identify bottlenecks"),
            ("•", "Continuous improvement based on outcome data"),
        ]),
        ("PILLAR 4 — COMMUNICATION", [
            ("•", "Over-communicate with clients — they always want more updates, not fewer"),
            ("•", "Respond to candidates within 24 hours, always"),
            ("•", "Be honest about bad news faster than you deliver good news"),
            ("•", "Set expectations early and beat them consistently"),
        ]),
        ("PILLAR 5 — BUSINESS DEVELOPMENT", [
            ("•", "Never stop building your pipeline — even when fully booked"),
            ("•", "Prioritize retention (repeat business) over acquisition (new clients)"),
            ("•", "Build your brand through content, referrals, and reputation"),
            ("•", "Track your BD metrics with the same rigor as your delivery metrics"),
        ]),
        ("MONTHLY SELF-ASSESSMENT", [
            "Score yourself 1–10 on each pillar monthly. Any score below 7 needs a focused improvement plan.",
            ("•", "Market Knowledge: ___/10"),
            ("•", "Relationships: ___/10"),
            ("•", "Process: ___/10"),
            ("•", "Communication: ___/10"),
            ("•", "Business Development: ___/10"),
        ]),
    ])

doc("11_BONUSES/Recruiting_Agency_Growth_Roadmap.docx",
    "Recruiting Agency Growth Roadmap",
    "Recruiting Agency Operating System | Bonuses",
    [
        ("STAGE 1 — ESTABLISH (Year 1: $0–$200K)", [
            ("•", "Define your niche: role type + industry + geography"),
            ("•", "Build your legal foundation: entity, contracts, insurance"),
            ("•", "Set up core tools: ATS, LinkedIn Recruiter, email, calendar"),
            ("•", "Make your first 10 client calls per week, consistently"),
            ("•", "First placement: prioritize speed over fee optimization"),
            ("•", "Target: 1–2 placements per month; 8–10 by year end"),
        ]),
        ("STAGE 2 — GROW (Year 2–3: $200K–$600K)", [
            ("•", "Build a client base of 5–10 active accounts"),
            ("•", "Hire your first support: virtual assistant or junior recruiter"),
            ("•", "Develop repeatable systems for sourcing, screening, and client management"),
            ("•", "Start content marketing: 3 LinkedIn posts per week minimum"),
            ("•", "Launch a referral program"),
            ("•", "Target: 3–5 placements per month; consistent $50K+ months"),
        ]),
        ("STAGE 3 — SCALE ($600K–$2M)", [
            ("•", "Hire 2–4 recruiters and a dedicated BD person"),
            ("•", "Specialize further: two or three distinct sub-niches"),
            ("•", "Implement retained search for senior roles"),
            ("•", "Build team playbooks and training programs"),
            ("•", "Track team KPIs and implement performance management"),
            ("•", "Target: $100K+ months; 8–15 placements per month"),
        ]),
        ("STAGE 4 — LEAD ($2M+)", [
            ("•", "Vertical team leads for each specialty"),
            ("•", "Operations manager to run day-to-day"),
            ("•", "Expand to additional niche verticals or geographies"),
            ("•", "Build employer brand and inbound lead engine"),
            ("•", "M&A: Acquire smaller agencies or books of business"),
            ("•", "Target: $1M+ per vertical annually"),
        ]),
        ("KEY MILESTONES TO CELEBRATE", [
            ("•", "First placement"),
            ("•", "First $10K month"),
            ("•", "First $50K month"),
            ("•", "First hired team member"),
            ("•", "First $100K month"),
            ("•", "First $1M year"),
        ]),
    ])

print("✓ 11_BONUSES complete")
print("PART 4 DONE")
