export const ERROR_CODES = {
  UNAUTHORIZED:     "UNAUTHORIZED",
  FORBIDDEN:        "FORBIDDEN",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND:        "NOT_FOUND",
  INTERNAL_ERROR:   "INTERNAL_ERROR",
  QUOTA_EXCEEDED:   "QUOTA_EXCEEDED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
